demo1

diff --git a/.github/workflows/healthz.yml b/.github/workflows/healthz.yml
--- a/.github/workflows/healthz.yml
+++ b/.github/workflows/healthz.yml
@@ -29,5 +29,5 @@ jobs:
       - name: Install dependencies
         run: npm install
         
-      - name: Execute 1 for failure
-        run: exit 1
+      # - name: Execute 1 for failure
+      #   run: exit 1
