changed github action file

diff --git a/.github/workflows/healthz.yml b/.github/workflows/healthz.yml
--- a/.github/workflows/healthz.yml
+++ b/.github/workflows/healthz.yml
@@ -20,9 +20,10 @@ jobs:
       postgres:
         image: postgres:16
         env:
+          POSTGRES_DB: ${{ secrets.DB_NAME }}
           POSTGRES_USER: ${{ secrets.DB_USER }}
           POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
-          POSTGRES_DB: ${{ secrets.DB_NAME }}
+          POSTGRES_PORT: 5432
         ports:
           - 5432:5432
         options: >-
@@ -32,6 +33,22 @@ jobs:
           --health-retries 5
 
     steps:
+      - name: Install PostgreSQL client
+        run: |
+          apt-get update
+          apt-get install --yes postgresql-client
+      # queries database with postgres client
+      - name: Query database
+        run: psql -h $POSTGRES_HOST -d $POSTGRES_DB -U $POSTGRES_USER -c 'SELECT 1;'
+        env:
+          # postgress password is required; alternatively, you can run:
+          # `PGPASSWORD=postgres_password psql ...`
+          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
+          POSTGRES_DB: ${{ secrets.DB_NAME }}
+          POSTGRES_USER: ${{ secrets.DB_USER }}
+          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
+          POSTGRES_HOST: ${{ secrets.DB_HOST }}
+
       - name: Check out code
         uses: actions/checkout@v2
 
@@ -39,22 +56,22 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
-      - name: Check Postgres connection with password
-        run: |
-          # Use 'pg' module for secure password handling
-          PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h $DB_HOST -U $DB_USER -d $DB_NAME -t -c "SELECT 1;" >/dev/null 2>&1
+      # - name: Check Postgres connection with password
+      #   run: |
+      #     # Use 'pg' module for secure password handling
+      #     PGPASSWORD=${{ secrets.DB_PASSWORD }} psql -h $DB_HOST -U $DB_USER -d $DB_NAME -t -c "SELECT 1;" >/dev/null 2>&1
     
-          if [[ $? -eq 0 ]]; then
-            echo "Postgres connection successful!"
-          else
-            echo "Postgres connection failed!"
-            exit 1
-          fi
+      #     if [[ $? -eq 0 ]]; then
+      #       echo "Postgres connection successful!"
+      #     else
+      #       echo "Postgres connection failed!"
+      #       exit 1
+      #     fi
     
-        env:
-          DB_HOST: ${{ secrets.DB_HOST }}
-          DB_USER: ${{ secrets.DB_USER }}
-          DB_NAME: ${{ secrets.DB_NAME }}
+      #   env:
+      #     DB_HOST: ${{ secrets.DB_HOST }}
+      #     DB_USER: ${{ secrets.DB_USER }}
+      #     DB_NAME: ${{ secrets.DB_NAME }}
 
       - name: Install dependencies
         run: npm install
